#!/usr/bin/env tsx
/**
 * Australian Law MCP — Ingestion Pipeline
 *
 * Reads from data/census.json (generated by census.ts) and fetches all ingestable
 * Australian federal legislation from legislation.gov.au using:
 * 1. OData API for metadata (version dates, register IDs)
 * 2. EPUB XHTML endpoint for actual legislation text
 *
 * Data is sourced under Creative Commons Attribution 4.0 International (CC BY 4.0).
 *
 * Features:
 *   - Resume support: skips laws that already have seed files in data/seed/
 *   - Progress logging every 10 laws
 *   - Rate limiting: 500ms minimum between requests
 *
 * Usage:
 *   npm run ingest                    # Full ingestion from census
 *   npm run ingest -- --limit 5       # Test with 5 acts
 *   npm run ingest -- --skip-fetch    # Reuse cached HTML source pages
 *   npm run ingest -- --resume        # Skip acts that already have seed files (default: on)
 *   npm run ingest -- --no-resume     # Re-fetch all acts even if seed exists
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { fetchLegislationHtml } from './lib/fetcher.js';
import { parseAustralianHtml, type ActIndexEntry, type ParsedAct } from './lib/parser.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SOURCE_DIR = path.resolve(__dirname, '../data/source');
const SEED_DIR = path.resolve(__dirname, '../data/seed');
const CENSUS_PATH = path.resolve(__dirname, '../data/census.json');

interface CensusLaw {
  id: string;
  title: string;
  identifier: string;
  url: string;
  year: number;
  number: number;
  status: string;
  is_principal: boolean;
  category: string;
  classification: string;
  ingested: boolean;
  provision_count: number | null;
  ingestion_date: string | null;
}

interface CensusFile {
  schema_version: string;
  jurisdiction: string;
  jurisdiction_name: string;
  portal: string;
  census_date: string;
  agent: string;
  summary: {
    total_laws: number;
    ingestable: number;
    ocr_needed: number;
    inaccessible: number;
    excluded: number;
  };
  laws: CensusLaw[];
}

function parseArgs(): { limit: number | null; skipFetch: boolean; resume: boolean } {
  const args = process.argv.slice(2);
  let limit: number | null = null;
  let skipFetch = false;
  let resume = true; // Default: resume (skip existing seeds)

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--limit' && args[i + 1]) {
      limit = parseInt(args[i + 1], 10);
      i++;
    } else if (args[i] === '--skip-fetch') {
      skipFetch = true;
    } else if (args[i] === '--no-resume') {
      resume = false;
    } else if (args[i] === '--resume') {
      resume = true;
    }
  }

  return { limit, skipFetch, resume };
}

/**
 * Load ingestable acts from census.json, converting to ActIndexEntry format.
 */
function loadCensus(): ActIndexEntry[] {
  if (!fs.existsSync(CENSUS_PATH)) {
    console.error(`Census file not found: ${CENSUS_PATH}`);
    console.error('Run: npx tsx scripts/census.ts');
    process.exit(1);
  }

  const census: CensusFile = JSON.parse(fs.readFileSync(CENSUS_PATH, 'utf-8'));
  console.log(`  Census: ${census.summary.total_laws} total, ${census.summary.ingestable} ingestable`);

  const ingestable = census.laws.filter(l => l.classification === 'ingestable');

  return ingestable.map(law => ({
    id: law.id,
    title: law.title,
    year: law.year,
    titleId: law.identifier,
    url: law.url,
    status: (law.status === 'in_force' ? 'in_force' :
             law.status === 'amended' ? 'amended' :
             law.status === 'repealed' ? 'repealed' : 'in_force') as ActIndexEntry['status'],
  }));
}

async function fetchAndParseActs(acts: ActIndexEntry[], skipFetch: boolean, resume: boolean): Promise<void> {
  console.log(`\nProcessing ${acts.length} federal acts...\n`);

  fs.mkdirSync(SOURCE_DIR, { recursive: true });
  fs.mkdirSync(SEED_DIR, { recursive: true });

  let processed = 0;
  let skipped = 0;
  let failed = 0;
  let totalProvisions = 0;
  const failedActs: Array<{ act: string; reason: string }> = [];
  const startTime = Date.now();

  for (const act of acts) {
    const sourceFile = path.join(SOURCE_DIR, `${act.id}.html`);
    const seedFile = path.join(SEED_DIR, `${act.id}.json`);

    // Resume support: skip if seed already exists
    if (resume && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8'));
        const provCount = existing.provisions?.length ?? 0;
        totalProvisions += provCount;
        skipped++;
        processed++;
        // Log every 100 skipped for feedback
        if (skipped % 100 === 0) {
          console.log(`  Skipped ${skipped} cached acts so far...`);
        }
        continue;
      } catch {
        // Corrupt seed file, re-fetch
      }
    }

    try {
      let html: string;
      let versionInfo = null;

      if (fs.existsSync(sourceFile) && skipFetch) {
        html = fs.readFileSync(sourceFile, 'utf-8');
      } else {
        const fetchIdx = processed - skipped + 1;
        const total = acts.length - skipped;
        process.stdout.write(`  [${fetchIdx}/${total}] Fetching ${act.title}...`);
        const result = await fetchLegislationHtml(act.titleId);
        versionInfo = result.versionInfo;

        if (result.status !== 200) {
          console.log(` HTTP ${result.status}`);
          failedActs.push({ act: act.title, reason: `HTTP ${result.status}` });
          failed++;
          processed++;
          continue;
        }

        if (!result.body || result.body.length < 500) {
          console.log(` Empty or too small response (${result.body?.length ?? 0} bytes)`);
          failedActs.push({ act: act.title, reason: `empty (${result.body?.length ?? 0} bytes)` });
          failed++;
          processed++;
          continue;
        }

        html = result.body;
        fs.writeFileSync(sourceFile, html);
        console.log(` OK (${(html.length / 1024).toFixed(0)} KB)`);
      }

      const parsed = parseAustralianHtml(html, act, versionInfo);
      fs.writeFileSync(seedFile, JSON.stringify(parsed, null, 2));
      totalProvisions += parsed.provisions.length;

      const fetchedCount = processed - skipped + 1;
      if (fetchedCount % 10 === 0) {
        const elapsed = ((Date.now() - startTime) / 1000 / 60).toFixed(1);
        console.log(`    -> ${parsed.provisions.length} provisions | Total: ${totalProvisions} provisions | ${elapsed} min elapsed`);
      } else {
        console.log(`    -> ${parsed.provisions.length} provisions, ${parsed.definitions.length} definitions`);
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      console.log(`  ERROR ${act.title}: ${msg.substring(0, 120)}`);
      failedActs.push({ act: act.title, reason: msg.substring(0, 120) });
      failed++;
    }

    processed++;
  }

  const elapsed = ((Date.now() - startTime) / 1000 / 60).toFixed(1);

  console.log(`\n${'='.repeat(60)}`);
  console.log(`Ingestion Summary`);
  console.log(`${'='.repeat(60)}`);
  console.log(`  Processed: ${processed}`);
  console.log(`  Skipped (cached): ${skipped}`);
  console.log(`  Failed: ${failed}`);
  console.log(`  Total provisions: ${totalProvisions}`);
  console.log(`  Time: ${elapsed} minutes`);

  if (failedActs.length > 0) {
    console.log(`\nFailed acts (${failedActs.length}):`);
    for (const f of failedActs) {
      console.log(`  ${f.act.padEnd(60)} [${f.reason}]`);
    }
  }
}

async function main(): Promise<void> {
  const { limit, skipFetch, resume } = parseArgs();

  console.log('Australian Law MCP — Ingestion Pipeline');
  console.log('========================================\n');
  console.log(`  Source: Federal Register of Legislation (legislation.gov.au)`);
  console.log(`  Method: OData API + EPUB XHTML endpoint`);
  console.log(`  License: CC BY 4.0`);
  console.log(`  Resume: ${resume ? 'yes (skip existing seeds)' : 'no (re-fetch all)'}`);

  if (limit) console.log(`  --limit ${limit}`);
  if (skipFetch) console.log(`  --skip-fetch`);

  const acts = loadCensus();
  const toProcess = limit ? acts.slice(0, limit) : acts;
  await fetchAndParseActs(toProcess, skipFetch, resume);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
